# Generated by Django 2.2 on 2019-04-28 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_order_items'),
        ('products', '0003_auto_20190428_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='order',
        ),
        migrations.AddField(
            model_name='item',
            name='order',
            field=models.ManyToManyField(blank=True, null=True, related_name='orders_item', to='orders.Order'),
        ),
    ]
