# Generated by Django 2.2 on 2019-05-01 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_order_items'),
        ('products', '0005_remove_item_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='order',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='orders.Order'),
        ),
    ]
