# Generated by Django 2.2 on 2019-04-28 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
    ]
