# Generated by Django 2.2 on 2019-05-01 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
    ]
